### ISSUE TITLE
History function does not display commands in reverse chronological order

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#182] opened 2019-04-04 13:32 UTC
**Describe the bug**
Results shown are in reverse lexicographical order rather than in reverse chronological which is stated in user guide.

**To Reproduce**
1. Enter history
2. See error in the results 

**Expected behavior**
A history of commands typed in should appear in reverse chronological manner.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/35647582/55453711-8d803a80-560f-11e9-8708-2c676910e33f.png)

**Additional context**

<hr>

**Reported by:** @shengkok
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#95]</sub>

**Comment by Creastery** [comment] 2019-04-04 14:58
Duplicate of #178

**Comment by Creastery** [comment] 2019-04-04 14:59
Thanks for the feedback.
We will update and fix the history command accordingly.

**Closed as completed** 2019-04-04 15:36 UTC
Labels: severity.Medium, type.FunctionalityBug, response.Accepted
