### ISSUE TITLE
Adding more than 20 MCs

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#179] opened 2019-04-04 13:30 UTC
**Describe the bug**
I can add a 20MC module which does not make sense

**To Reproduce**
add code/CS2222 name/Programming Methodology credits/20 tag/programming tag/algorithms tag/c tag/imperative

**Expected behavior**
It should throw an error for invalid Modular credits

**Screenshots**
<img width="920" alt="Screen Shot 2019-04-03 at 12 46 03 PM" src="https://user-images.githubusercontent.com/43682311/55453435-78ef7280-560e-11e9-8d76-5aada2d319d6.png">

**Additional context**

<hr>

**Reported by:** @matthiaslum
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#59]</sub>

**Comment by Creastery** [comment] 2019-04-04 14:29
We do not restrict the number of modular credits (MCs) that can be assigned to a `Module` to 20 MCs.
For instance, users may want to add a module with 20 MCs assigned to indicate Advanced Placement Credits (APC) under Unrestricted Elective requirements.

Nonetheless, thanks for the feedback.

**Closed as completed by Creastery** 2019-04-04 14:29 UTC
Labels: severity.Low, response.NotInScope

**Comment by Creastery** [comment] 2019-04-04 15:07
Duplicate of #184
